FROM php:8.0-apache
RUN docker-php-ext-install mysqli && docker-php-ext-enable mysqli
RUN apt-get update && apt-get upgrade -y

#FROM php:5.6-apache
#RUN docker-php-ext-install mysqli

#FROM nginx:alpine
#COPY . /usr/share/nginx/html